### ISSUE TITLE
Descrizione alternativa delle immagini

### ISSUE THREAD

**Issue by EdoPut** [MozillaItalia/firefoxos-quick-guide#42]
Tutte le immagini devono avere la descrizione alternativa.

La cosa migliore sarebbe implementare un test come dovremmo farlo per #23

**Comment by Mte90** [comment]
bisogna vedere se su leanpub è obbligatorio

**Comment by EdoPut** [comment]
Si, LeanPub aggiunge la descrizione alternativa sotto le immagini

**Comment by EdoPut** [comment]
Ho cominciato a lavorare sul problema, ecco dove sono arrivato finora. [test](https://github.com/EdoPut/firefoxos-quick-guide-test)

**Comment by Mte90** [comment]
se il tuo script funziona, mi dedico io a questo lavoro :-)

**Comment by EdoPut** [comment]
Lo script dice:

manca la descrizione alternativa in firefoxos-quick-guide/manuscript/webide.md alla linea 41
manca la descrizione alternativa in firefoxos-quick-guide/manuscript/webide.md alla linea 55

buon lavoro!

**Comment by Mte90** [comment]
per soli due fix di questo tipo ho preferito fare prima modificando direttamente qui.
