### ISSUE TITLE
Github Pages

### ISSUE THREAD

**Issue by EdoPut** [MozillaItalia/firefoxos-quick-guide#48]
Forse faremmo una bella figura con una pagina dedicata? Avere LeanPub e la pagina potrebbe essere controproducente

**Comment by Mte90** [comment]
Vediamo come viene il pdf al limite possiamo fare la versione web che carica la versione html generata da leanpub

**Comment by Mte90** [comment]
Ho abilitato la versione web su Leanpub, ogni volta che verrà generato il libro verrà generata anche una versione web. Certo quando lo pubblicheremo

**Comment by EdoPut** [comment]
Ottimo, diciamo addio a questo problema allora
