### ISSUE TITLE
rimuovere 0.3

### ISSUE THREAD

**Issue by EdoPut** [MozillaItalia/firefoxos-quick-guide#63]
D'ora in poi vorrei poter lavorare con un branch per ogni aggiunta/richiesta/problema, anche perché continuare a fare aggiunte a master non ha senso se non siamo sicuri del lavoro che stiamo facendo, visto che viene pubblicata ad ogni commit una nuova versione del libro.

**Comment by Mte90** [comment]
Se non le facciamo sul master non possiamo vedere se la compilazione ha successo.
Un branch per aggiunte e richiesta non è sbagliato come idea ma per risolvere i problemi ci serve il master.

**Comment by EdoPut** [comment]
fortunatamente essendo il libro in markdown per il 90% del lavoro possiamo fare le preview in locale, quelle tre quattro estensioni specifiche di leanpub possono essere controllate facendo il merge su master, quindi direi che siamo d'accordo :+1:

**Comment by Mte90** [comment]
Si certo il grosso dei problemi li abbiamo con leanpub, quindi per la maggioranza dei fix non è un problema.
Approved :-)

**Comment by Mte90** [comment]
pensiamo anche all'eliminazione di rami obsoleti oramai integrati dopo il #74

**Comment by EdoPut** [comment]
cosa voleva dire 0.3?  era quella che abbiamo chiamato old?

**Comment by Mte90** [comment]
direi di rimuovere i vari rami obsoleti

**Comment by EdoPut** [comment]
tutti quanti? avevi detto che volevi tenere old perché comunque era una versione completamente tradotta

**Comment by Mte90** [comment]
uhm hai ragione, incomincio a invecchiare.
