### ISSUE TITLE
Marketplace, riassunto

### ISSUE THREAD

**Issue by EdoPut** [MozillaItalia/firefoxos-quick-guide#70]
`======= Spero che la lettura di questa veloce guida sia stata piacevole. Ho in mente di aggiornare
e ampliare spesso questa guida,`

A cosa servono i segni di uguaglianza?

**Comment by Mte90** [comment]
in markdown dovrebbero mettere una linea se non hanno testo sulla stessa riga

**Comment by EdoPut** [comment]
ho spostato il testo in modo che appaia questa riga di interruzione

**Comment by EdoPut** [comment]
La riga non viene inserita, a questo punto ha anche senso togliere questa interruzione

**Comment by Mte90** [comment]
esegui capitano!
