### ISSUE TITLE
Pubblicazione

### ISSUE THREAD

**Issue by EdoPut** [MozillaItalia/firefoxos-quick-guide#74]
Siamo arrivati al punto, ritengo che il testo sia pronto per la pubblicazione e vorrei fosse disponibile prima del Codemotion di fine Marzo.

**Comment by Mte90** [comment]
ok lo pubblichiamo come beta?

**Comment by Mte90** [comment]
Però lo facciamo quando abbiamo spostato il repo sull'organizzazione così diventa ufficiale?

**Comment by EdoPut** [comment]
Per adesso possiamo fare anche senza il trasferimento, l'integrazione con LeanPub un'inezia da fare dopo il trasferimento.

**Comment by Mte90** [comment]
Per una questione di immagine se lo presentiamo invece di un mio progetto ma di un progetto comunitario è più faigo.
