### ISSUE TITLE
Meta Ticket Codemotion Roma 2015

### ISSUE THREAD

**Issue by Mte90** [MozillaItalia/firefoxos-quick-guide#76]
In questo ticket saranno raccolti tutti i feedback durante l'evento e post evento per l'ebook [beta].
Io modificherò questo ticket (senza aggiungerne di nuovi) dando la possibilità agli altri di popolarlo così farà da indice.

Link ebook con le varie informazioni: http://www.mozillaitalia.org/home/2015/03/19/imparare-a-sviluppare-per-firefox-os-la-guida-veloce/

# Typo rilevati
* Errore lettera accentata ultima pagina per la parola comunit[à] nei vari file esportati non è riconosciuta, forse dobbiamo controllare tutte le accentate e contattare leanpub

# Migliorie
* Screenshot di Firefox OS 1.1 simulator nella parte dedicata all'app memos
* Miaapplicazione, alcuni pensano che è un boilerplate

**Comment by EdoPut** [comment]
Dani non penso che sia una buona idea, i ticket servono apposta per poter tenere traccia dei singoli problemi, se li riunisci tutti in un unico poi come facciamo a controllare ogni singolo problema. Mettiamo una nuova etichetta **feedback** così possiamo indirizzare subito questi problemi

**Comment by EdoPut** [comment]
Inoltre i **typo** hanno già la loro etichetta quindi basterebbe usare quella

**Comment by Mte90** [comment]
Mi serviva come raccolta durante il codemotion per verificare successivamente le varie segnalazioni, un meta ticket potremmo definirlo

**Comment by EdoPut** [comment]
ok però spezzalo nei vari ticket così possiamo tenere conto dei problemi singoli. Ricordati che se un utente di Github ci lascia un ticket noi possiamo modificarlo a nostro piacimento per adattarlo al sistema che abbiamo

**Comment by Mte90** [comment]
Si tranquillo, quei feedback me li hanno dati di persona quindi li ho inseriti direttamente, anche perchè la sto rileggendo dopo averla stampata.
