### ISSUE TITLE
Firefox OS 1.1

### ISSUE THREAD

**Issue by Mte90** [MozillaItalia/firefoxos-quick-guide#78]
Direi di rimuovere i testi ripetuti in questa parte che sono stati già spiegati nel capitolo precedente dedicato al webide in modo da renderlo più compatto.
Lo farò dopo la revisione, che ne dite?

**Comment by Mte90** [comment]
Ci sono dei pezzi presi paro paro dal webide o viceversa.
Siccome il capitolo su questo è successivo io direi di rimuovere queste parti, dicendo che è spiegato nel capitolo precedente.
Che ne dici @EdoPut? faccio una pull request?

**Comment by EdoPut** [comment]
Vediamo cosa riesci a fare

**Comment by Mte90** [comment]
detta così è una sfida per farmi fare danni :grinning:
