### ISSUE TITLE
Rimuovere i vecchi screen

### ISSUE THREAD

**Issue by Mte90** [MozillaItalia/firefoxos-quick-guide#79]
Ci sono screen dell'app manager da aggiornare con quelli del webide.
Inoltre vanno aggiornati anche gli screen dei tool di sviluppo.

**Comment by EdoPut** [comment]
aspetta aspetta, non ci possono essere, abbiamo rimosso le immagini di appmanager!

**Comment by Mte90** [comment]
ne è rimasta una in simulator 1.1, direi che è il caso di fare un check.

**Comment by EdoPut** [comment]
:frowning:
