### ISSUE TITLE
Link errati

### ISSUE THREAD

**Issue by git4r** [MozillaItalia/firefoxos-quick-guide#82]
Salve,

Durante la lettura della guida ho trovato dei link che non corrispondono all'argomento citato.
In particolare mi riferisco al capitolo "la prima app", in realtà questi collegamenti sono stati mischiati, almeno nel documento che ho scaricato io:

| pag | nota |
-------|-------
27     | 48
28     | 49
32     | 52
36     | a
37     | 53
39     | 54
41     | 56

Questi sono quelli evidenti fino a questo capitolo.
Spero di essere stato utile.

**Comment by EdoPut** [comment]
@git4r grazie per la segnalazione, vedo cosa riesco a fare

**Comment by EdoPut** [comment]
- [ ] firstapp.md, nota 48 il link a MDN non è corretto
- [ ] firstapp.md, nota 49, invece di puntare a building blocks punta a json.org
- [ ] firstapp.md, nota 52, invece di puntare a IndexedDB punta a building blocks
- [ ] firstapp.md, nota a, invece di puntare a Promises punta alle web activities

**Comment by EdoPut** [comment]
Ok, adesso i link puntano alle risorse correte ma continua a persistere il #59, vado a vedere se nella mailing list c'è qualche soluzione
